AWSTemplateFormatVersion: "2010-09-09"
Description: "The routes configuration for jakegillespie.me."

Parameters:

  AppStackName:
    Type: String
    Description: "The name of the parent app stack"

Resources:

  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "jakegillespie.me."

  RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-dns"
        HostedZoneId:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-hosted-zone"
      HostedZoneId: !Ref HostedZone
      Name: "jakegillespie.me."
      Type: "A"

  ProjectsRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-dns"
        HostedZoneId:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-hosted-zone"
      HostedZoneId: !Ref HostedZone
      Name: "projects.jakegillespie.me."
      Type: "A"

  ProjectsStagingRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-dns"
        HostedZoneId:
          Fn::ImportValue: !Sub "${AppStackName}-load-balancer-hosted-zone"
      HostedZoneId: !Ref HostedZone
      Name: "projects-staging.jakegillespie.me."
      Type: "A"
