AWSTemplateFormatVersion: "2010-09-09"
Description: "The GoCD server resources that enable it to support jakegillespie.me."
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "eu-west-2a"
      ImageId: !Ref GoServerAMI
      InstanceInitiatedShutdownBehavior: "terminate"
      InstanceType: "t2.medium"
      KeyName: "jakegillespie"
      SecurityGroupIds:
        - Fn::ImportValue: !Join [ "-", [ !Ref NetworkStackName, "server-security-group" ] ]
      SubnetId:
        Fn::ImportValue: !Join [ "-", [ !Ref NetworkStackName, "subnet-a" ] ]
  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-399'
      Port: 8153
      Protocol: "HTTP"
      Targets:
        -
          Id: !Ref ServerEC2
          Port: 8153
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: !Join [ "-", [ !Ref NetworkStackName, "vpc" ] ]
  InsecureListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        -
          TargetGroupArn: !Ref TargetGroup
          Type: "forward"
      Conditions:
        -
          Field: 'path-pattern'
          Values:
            - "/go/*"
      ListenerArn: !Ref InsecureListener
      Priority: 1
  ServerSecureListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        -
          TargetGroupArn: !Ref TargetGroup
          Type: "forward"
      Conditions:
        -
          Field: 'path-pattern'
          Values:
            - "/go/*"
      ListenerArn: !Ref SecureListener
      Priority: 1
