AWSTemplateFormatVersion: "2010-09-09"
Description: "The GoCD server resources that enable it to support jakegillespie.me."

Parameters:

  AppStackName:
    Type: String
    Description: "The name of the parent app stack"

  GoServerAMI:
    Type: String
    Description: "The ID of the GoCD Server AMI"

Resources:

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "eu-west-2a"
      ImageId: !Ref GoServerAMI
      InstanceInitiatedShutdownBehavior: "terminate"
      InstanceType: "t2.medium"
      KeyName: "jakegillespie"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${AppStackName}-allow-ssh"
        - !Ref SecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub "${AppStackName}-subnet-a"

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-399'
      Port: 8153
      Protocol: "HTTP"
      Targets:
        -
          Id: !Ref EC2Instance
          Port: 8153
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: !Sub "${AppStackName}-vpc"

  InsecureListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        -
          TargetGroupArn: !Ref TargetGroup
          Type: "forward"
      Conditions:
        -
          Field: 'path-pattern'
          Values:
            - "/go/*"
      ListenerArn:
        Fn::ImportValue: !Sub "${AppStackName}-insecure-listener"
      Priority: 1

  ServerSecureListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        -
          TargetGroupArn: !Ref TargetGroup
          Type: "forward"
      Conditions:
        -
          Field: 'path-pattern'
          Values:
            - "/go/*"
      ListenerArn:
        Fn::ImportValue: !Sub "${AppStackName}-secure-listener"
      Priority: 1

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allows traffic on 8153 from the load balancer security group"
      SecurityGroupIngress:
        -
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub "${AppStackName}-load-balancer-security-group"
          IpProtocol: "tcp"
          FromPort: 8153
          ToPort: 8153
      VpcId:
        Fn::ImportValue: !Sub "${AppStackName}-vpc"
