AWSTemplateFormatVersion: "2010-09-09"
Description: "All user-related resources for jakegillespie.me"

Resources:

  S3ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      # TODO Rename this to "get-credentials" when the legacy role has been removed.
      RoleName: "get-credentials-from-s3"

  S3ReadOnlyInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref S3ReadOnlyRole
