AWSTemplateFormatVersion: "2010-09-09"
Description: "The networking infrastructure for jakegillespie.me."

Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "172.16.0.0/16"
      EnableDnsHostnames: "true"

  SubnetA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "eu-west-2a"
      CidrBlock: "172.16.0.0/24"
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref VPC

  SubnetB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "eu-west-2b"
      CidrBlock: "172.16.1.0/24"
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref VPC

  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC

  SubnetARouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetA

  SubnetBRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetB

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  Route:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

Outputs:

  VPC:
    Description: "The VPC ID"
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-vpc"

  SubnetA:
    Description: "The ID of subnet A"
    Value: !Ref SubnetA
    Export:
      Name: !Sub "${AWS::StackName}-subnet-a"

  SubnetB:
    Description: "The ID of subnet B"
    Value: !Ref SubnetB
    Export:
      Name: !Sub "${AWS::StackName}-subnet-b"
